var annotated_dup =
[
    [ "ApproachCircleScript", "class_approach_circle_script.html", "class_approach_circle_script" ],
    [ "Arrow", "class_arrow.html", "class_arrow" ],
    [ "BasicArrow", "class_basic_arrow.html", null ],
    [ "BasicArrow", "class_basic_arrow.html", "class_basic_arrow" ],
    [ "CameraController", "class_camera_controller.html", "class_camera_controller" ],
    [ "Delayed", "class_delayed.html", "class_delayed" ],
    [ "FastArrow", "class_fast_arrow.html", "class_fast_arrow" ],
    [ "GameController", "class_game_controller.html", "class_game_controller" ],
    [ "ItemSpawner", "class_item_spawner.html", "class_item_spawner" ],
    [ "LoadSceneOnClick", "class_load_scene_on_click.html", "class_load_scene_on_click" ],
    [ "Mob1Movement", "class_mob1_movement.html", "class_mob1_movement" ],
    [ "Mob2Movement", "class_mob2_movement.html", "class_mob2_movement" ],
    [ "MobHealth", "class_mob_health.html", "class_mob_health" ],
    [ "OsuCircle", "class_osu_circle.html", "class_osu_circle" ],
    [ "PauseMenu", "class_pause_menu.html", "class_pause_menu" ],
    [ "Pickup", "class_pickup.html", "class_pickup" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "QuitOnClick", "class_quit_on_click.html", "class_quit_on_click" ],
    [ "SceneController", "class_scene_controller.html", "class_scene_controller" ],
    [ "SelectOnInput", "class_select_on_input.html", "class_select_on_input" ],
    [ "ShootingAimLine", "class_shooting_aim_line.html", "class_shooting_aim_line" ],
    [ "SpawnController", "class_spawn_controller.html", "class_spawn_controller" ],
    [ "SpawnPickups", "class_spawn_pickups.html", "class_spawn_pickups" ],
    [ "Spell", "class_spell.html", "class_spell" ],
    [ "SpellController", "class_spell_controller.html", "class_spell_controller" ],
    [ "UIController", "class_u_i_controller.html", "class_u_i_controller" ]
];